package scraper


var NationsCode = map[string]string{
	"Afganistán" : "Afghanistan_AF",
	"Åland" : "Åland_AX",
	"Albania" : "Albania_AL",
	"Argelia" : "Algeria_DZ",
	"Samoa Americana" : "American Samoa_AS",
	"Andorra" : "Andorra_AD",
	"Angola" : "Angola_AO",
	"Anguila" : "Anguilla_AI",
	"Antártico" : "Antarctica_AQ",
	"Antigua y Barbuda" : "Antigua and Barbuda_AG",
	"Argentina" : "Argentina_AR",
	"Armenia" : "Armenia_AM",
	"Aruba" : "Aruba_AW",
	"Isla Ascensión" : "Ascension Island_AC",
	"Australia" : "Australia_AU",
	"Austria" : "Austria_AT",
	"Azerbaiyán" : "Azerbaijan_AZ",
	"Bahamas" : "Bahamas_BS",
	"Bahréin" : "Bahrain_BH",
	"Bangladesh" : "Bangladesh_BD",
	"Barbados" : "Barbados_BB",
	"Bielorrusia" : "Belarus_BY",
	"Bélgica" : "Belgium_BE",
	"Belice" : "Belize_BZ",
	"Benín" : "Benin_BJ",
	"Bermudas" : "Bermuda_BM",
	"Bután" : "Bhutan_BT",
	"Bolivia" : "Bolivia_BO",
	"Bonaire, San Estaquio y Saba" : "Bonaire, Saint Eustatius and Saba_BQ",
	"Bosnia-Herzegovina" : "Bosnia-Herzegovina_BA",
	"Botsuana" : "Botswana_BW",
	"Brasil" : "Brazil_BR",
	"Territorio Británico en el Océano Índico" : "British Indian Ocean Territory_IO",
	"Islas Vírgenes Británicas" : "British Virgin Islands_VG",
	"Brunei Darussalam" : "Brunei Darussalam_BN",
	"Bulgaria" : "Bulgaria_BG",
	"Burkina Faso" : "Burkina Faso_BF",
	"Burundi" : "Burundi_BI",
	"Camboya" : "Cambodia_KH",
	"Camerún" : "Cameroon_CM",
	"Canadá" : "Canada_CA",
	"Cabo Verde" : "Cape Verde	CV",
	"Catalunya" : "Catalonia_CAT",
	"Islas Caimán" : "Cayman Islands_KY",
	"República Centroafricana" : "Central African Republic_CF",
	"Chad" : "Chad_TD",
	"Chile" : "Chile_CL",
	"China (República Popular)" : "China (Peoples Republic of)_CN",
	"Isla de Navidad" : "Christmas Island_CX",
	"Islas Cocos" : "Cocos/Keeling Islands_CC",
	"Colombia" : "Colombia_CO",
	"Comoras" : "Comoros_KM",
	"Congo (República del)" : "Congo (Republic of the)_CG",
	"Islas Cook" : "Cook Islands_CK",
	"Costa Rica" : "Costa Rica_CR",
	"Croacia" : "Croatia_HR",
	"Cuba" : "Cuba_CU",
	"Curasao" : "Curação_CW",
	"Chipre" : "Cyprus_CY",
	"República Checa" : "Czech Republic_CZ",
	"República Democrática del Congo" : "Democratic Republic of the Congo_CD",
	"Dinamarca" : "Denmark_DK",
	"Yibuti" : "Djibouti_DJ",
	"Dominica" : "Dominica_DM",
	"República Dominicana" : "Dominican Republic_DO",
	"Timor Oriental" : "East Timor_TL",
	"Ecuador" : "Ecuador_EC",
	"Egipto" : "Egypt_EG",
	"El Salvador" : "El Salvador_SV",
	"Guinea Ecuatorial" : "Equatorial Guinea_GQ",
	"Eritrea" : "Eritrea_ER",
	"Estonia" : "Estonia_EE",
	"Etiopía" : "Ethiopia_ET",
	"Unión Europea" : "European Union_EU",
	"Islas Malvinas" : "Falkland Islands_FK",
	"Islas Feroe" : "Faroe Islands_FO",
	"Fiyi" : "Fiji_FJ",
	"Finlandia" : "Finland_FI",
	"Francia" : "France_FR",
	"Guayana Francesa" : "French Guiana_GF",
	"Polinesia Francesa" : "French Polynesia_PF",
	"Territorios Australes Franceses" : "French Southern and Antarctic Lands_TF",
	"Gabón" : "Gabon_GA",
	"Gambia" : "Gambia (The)_GM",
	"Georgia" : "Georgia_GE",
	"Alemania" : "Germany_DE",
	"Ghana" : "Ghana_GH",
	"Gibraltar" : "Gibraltar_GI",
	"Grecia" : "Greece_GR",
	"Groenlandia" : "Greenland_GL",
	"Granada" : "Grenada_GD",
	"Guadalupe" : "Guadeloupe_GP",
	"Guam" : "Guam_GU",
	"Guatemala" : "Guatemala_GT",
	"Guernesey" : "Guernsey_GG",
	"Guinea" : "Guinea_GN",
	"Guinea-Bissau" : "Guinea-Bissau_GW",
	"Guyana" : "Guyana_GY",
	"Haití" : "Haiti_HT",
	"Islas Heard y McDonald" : "Heard Island and McDonald Islands_HM",
	"Holanda (see netherlands)" : "Holland_NL",
	"Honduras" : "Honduras_HN",
	"Hong Kong" : "Hong Kong_HK",
	"Hungría" : "Hungary_HU",
	"Islandia" : "Iceland_IS",
	"India" : "India_IN",
	"Indonesia" : "Indonesia_ID",
	"Irán" : "Iran_IR",
	"Iraq" : "Iraq_IQ",
	"Irlanda" : "Ireland_IE",
	"Isla de Man" : "Isle of Man_IM",
	"Israel" : "Israel_IL",
	"Italia" : "Italy_IT",
	"Costa de Marfil" : "Ivory Coast_CI",
	"Jamaica" : "Jamaica_JM",
	"Japón" : "Japan_JP",
	"Isla de Jersey" : "Jersey_JE",
	"Jordania" : "Jordan_JO",
	"Kazajistán" : "Kazakhstan_KZ",
	"Kenia" : "Kenya_KE",
	"Kiribati" : "Kiribati_KI",
	"Corea (del Norte)" : "Korea (North)_KP",
	"Corea (del Sur)" : "Korea (South)_KO",
	"Kuwait" : "Kuwait_KW",
	"Kirguistán" : "Kyrgyzstan_KG",
	"Laos" : "Laos_LA",
	"Letonia" : "Latvia_LV",
	"Líbano" : "Lebanon_LB",
	"Lesotho" : "Lesotho_LS",
	"Liberia" : "Liberia_LR",
	"Libia" : "Libya_LY",
	"Liechtenstein" : "Liechtenstein_LI",
	"Lituania" : "Lithuania_LT",
	"Luxemburgo" : "Luxembourg_LU",
	"Macao" : "Macau_MO",
	"Macedonia (República de)" : "Macedonia (Republic of)_MK",
	"Madagascar" : "Madagascar_MG",
	"Malawi" : "Malawi_MW",
	"Malasia" : "Malaysia_MY",
	"Maldivas" : "Maldives_MV",
	"Malí" : "Mali_ML",
	"Malta" : "Malta_MT",
	"Islas Marshall" : "Marshall Islands_MH",
	"Martinica" : "Martinique_MQ",
	"Mauritania" : "Mauritania_MR",
	"Mauricio" : "Mauritius_MU",
	"Mayotte" : "Mayotte_YT",
	"México" : "Mexico_MX",
	"Micronesia (Estados Federados de)" : "Micronesia (Federated States of)_FM",
	"Moldavia" : "Moldova_MD",
	"Mónaco" : "Monaco_MC",
	"Mongolia" : "Mongolia_MN",
	"Montenegro" : "Montenegro_ME",
	"Montserrat" : "Montserrat_MS",
	"Marruecos" : "Morocco_MA",
	"Mozambique" : "Mozambique_MZ",
	"Myanmar" : "Myanmar_MM",
	"Namibia" : "Namibia_NA",
	"Nauru" : "Nauru_NR",
	"Nepal" : "Nepal_NP",
	"Países Bajos (Holanda)" : "Netherlands (Holland)_NL",
	"Antillas Nederlandesas (ya no existe)" : "Netherlands Antilles (no longer exists)_AN",
	"Nueva Caledonia" : "New Caledonia_NC",
	"Nueva Zelanda" : "New Zealand_NZ",
	"Nicaragua" : "Nicaragua_NI",
	"Níger" : "Niger_NE",
	"Nigeria" : "Nigeria_NG",
	"Niue" : "Niue_NU",
	"Isla Norfolk" : "Norfolk Island_NF",
	"Irlanda del Norte" : "Northern Ireland_UK",
	"Islas Marianas del Norte" : "Northern Mariana Islands_MP",
	"Noruega" : "Norway_NO",
	"Omán" : "Oman_OM",
	"Pakistán" : "Pakistan_PK",
	"Palau" : "Palau_PW",
	"Palestina" : "Palestinian Territories_PS",
	"Panamá" : "Panama_PA",
	"Papúa Nueva Guinea" : "Papua New Guinea_PG",
	"Paraguay" : "Paraguay_PY",
	"Perú" : "Peru_PE",
	"Filipinas" : "Philippines_PH",
	"Islas Pitcairn" : "Pitcairn Islands_PN",
	"Polonia" : "Poland_PL",
	"Portugal" : "Portugal_PT",
	"Puerto Rico" : "Puerto Rico_PR",
	"Qatar" : "Qatar_QA",
	"Reunión" : "Réunion_RE",
	"Rumania" : "Romania_RO",
	"Rusia" : "Russia_RU",
	"Ruanda" : "Rwanda_RW",
	"Santa Helena" : "Saint Helena_SH",
	"San Cristóbal y Nieves" : "Saint Kitts and Nevis_KN",
	"Santa Lucía" : "Saint Lucia_LC",
	"San Martín (Sint Maarten)" : "Saint Maarten_SX",
	"San Vicente y las Granadinas" : "Saint Vincent and the Grenadines_VC",
	"San Pedro y Miquelón" : "Saint-Pierre and Miquelon_PM",
	"San Marino" : "San Marino_SM",
	"Santo Tomé y Príncipe" : "São Tomé and Príncipe_ST",
	"Arabia Saudita" : "Saudi Arabia_SA",
	"Senegal" : "Senegal_SN",
	"Serbia" : "Serbia_RS",
	"Seychelles" : "Seychelles_SC",
	"Sierra Leona" : "Sierra Leone_SL",
	"Singapur" : "Singapore_SG",
	"Eslovaquia" : "Slovakia_SK",
	"Eslovenia" : "Slovenia_SI",
	"Islas Salomón" : "Solomon Islands_SB",
	"Somalia" : "Somalia_SO",
	"Sudáfrica" : "South Africa_ZA",
	"Islas Georgias del Sur y Sandwich del Sur" : "South Georgia and the South Sandwich Islands_GS",
	"Sudán del Sur" : "South Sudan_SS",
	"Unión Soviética (URSS)" : "Soviet Union (USSR)_SU",
	"España" : "Spain_ES",
	"Sri Lanka" : "Sri Lanka_LK",
	"Sudán" : "Sudan_SD",
	"Surinam" : "Suriname_SR",
	"Islas Svalbard y Jan Mayen" : "Svalbard and Jan Mayen Islands_SJ",
	"Swazilandia" : "Swaziland_SZ",
	"Suecia" : "Sweden_SE",
	"Suiza" : "Switzerland_CH",
	"Siria" : "Syria_SY",
	"Taiwán" : "Taiwan_TW",
	"Tayikistán" : "Tajikistan_TJ",
	"Tanzania" : "Tanzania_TZ",
	"Tailandia" : "Thailand_TH",
	"Togo" : "Togo_TG",
	"Tokelau" : "Tokelau_TK",
	"Tonga" : "Tonga_TO",
	"Trinidad y Tobago" : "Trinidad and Tobago_TT",
	"Túnez" : "Tunisia_TN",
	"Turquía" : "Turkey_TR",
	"Turkmenistán" : "Turkmenistan_TM",
	"Islas Turcas y Caicos" : "Turks and Caicos Islands_TC",
	"Tuvalu" : "Tuvalu_TV",
	"Uganda" : "Uganda_UG",
	"Ucrania" : "Ukraine_UA",
	"Emiratos Árabes Unidos" : "United Arab Emirates_AE",
	"Reino Unido (RU)" : "United Kingdom (UK)_UK",
	"Inglaterra": "United Kingdom (UK)_UK",
	"Estados Unidos (EEUU)" : "United States of America (USA)_US",
	"Uruguay" : "Uruguay_UY",
	"Islas Vírgenes de los Estados Unidos" : "US Virgin Islands_VI",
	"Uzbekistán" : "Uzbekistan_UZ",
	"Vanuatu" : "Vanuatu_VU",
	"Ciudad del Vaticano" : "Vatican City State_VA",
	"Venezuela" : "Venezuela_VE",
	"Vietnam" : "Vietnam_VN",
	"Wallis y Futuna" : "Wallis and Futuna_WF",
	"Samoa del Oeste" : "Western Samoa_WS",
	"Yemen" : "Yemen_YE",
	"Yugoslavia" : "Yugoslavia_YU",
	"Zambia" : "Zambia_ZM",
	"Zimbabue" : "Zimbabwe_ZW",
}
